alpha: 0.9999
learning_rate: 0.02
loss: squared_error
max_depth: 14
max_features: sqrt
max_leaf_nodes: 30
min_impurity_decrease: 0.0
min_samples_leaf: 2
min_samples_split: 7
min_weight_fraction_leaf: 0.0
n_estimators: 600
subsample: 0.7
